Script for t-test
CNERG/snippets pull request #1
Opened 2019-10-08 22:46 UTC by ypark234

This adds a script that runs two-sample t-test with two data sets.
t-test is a statistical calculation that can be used to determine if there is a statistically significant difference between two sample groups.
In this script, unpaired equal variance two-sample t-test will be conducted for comparison of data that are assumed to be taken from an identical distribution.

2019-10-10 20:26 UTC, bam241 commented
Maybe add some kind of readme to explain how to use and ref to the stats

2019-10-10 20:29 UTC, bam241 commented
maybe separate snippet and unit_tests

in this PR or a separate PR, maybe setup CI-testing ?

2019-10-10 21:02 UTC, kkiesling reviewed
Other thoughts to add:

2-D/3-D histogram of the p-values for like a mesh
write out the actual set of p-values (connecting them to the data sets/dicts that already exist)

Suggested structure changes:
1. expect users to provide two lists of data (not necessarily as a dictionary with keys) - perhaps two lists of tuples (data, standard error).
2. calculate t-test and return the data set with all the stats (np structured array? see line 212)
3. provide additional functions for writing that data set to a file and another function that can plot it in a histogram

Add a README

2019-10-10 21:02 UTC, kkiesling commented on stats/t_test.py
> +    data_2 = process_data(rd_2)
Since the idea is that someone could use this for any sort of data, someone may want to use this without having a file. I could think of using this by loading it as a module in another python script and passing it a data set. In that case, there would be no files to read in. Therefore, it might be better to have separate functions for loading/reading files and actually performing the t-test.

2019-10-10 21:02 UTC, kkiesling commented on stats/t_test.py
> +        stat[key] = (t_val, df, p_val, t_crit, reject)
would return this dict as output so that the user could write it or plot it

2019-10-10 21:02 UTC, kkiesling commented on stats/t_test.py
> +    # Plot histogram of p-values.
would make this as a new function

2019-10-22 02:17 UTC, gonuke commented on stats/t_test.py
> +    data_2 = process_data(rd_2)
This is a recurring theme across many projects - we need to focus on separating file I/O from processing data

2020-01-27 23:53 UTC, gonuke commented
Are we waiting on CI for this?

2020-01-27 23:57 UTC, ypark234 commented
I am adding README and making last few changes, while waiting for CI config is added by a separate PR.

2020-04-10 20:39 UTC, gonuke commented
Maybe I should clarify my earlier CI questions.... should I wait for CI to be implemented before merging this PR?  Or is this something that can be merged prior to CI being implemented?

2020-04-10 20:49 UTC, ypark234 commented
CI will be implemented in a separate PR.
I expect this PR to be merged after CI is properly added.

2020-04-19 14:29 UTC, ypark234 commented
This PR is ready to be reviewed.
(CI test for the repo still needs to be triggered properly.)

2020-04-20 19:15 UTC, kkiesling reviewed
This is a very well done and thorough "snippet"! I mostly just have questions.

The README has a lot of theory information in it and I am wondering if it is really necessary? I appreciate all the information, but I at the same time I think that the README for a script should really just include the information needed for the users to run the script. So that would basically be just information on how the input should be structured and how to run and then what the results should look like. I think it's plenty to just refer users to a resource to learn about the t-test if they don't know what it is. Though I also appreciate that you took all the time and effort to put the resource together. Maybe the "usage" and the background information parts of the README just need to be two separate documents?

On a different note, I think it's awesome that you have this structured so that one could just import the modules in a python script or actually run your script with command line arguments. Allows for a lot of different use which is nice.

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +Nuclear engineering relevant examples of such data include *k<sub>eff</sub>* and
this is a really helpful note on how this might be used in nuclear applications. Thanks for adding that!

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +## t-test?
why the question mark?

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +t-values are not in the units of the original data, but unitless.
```suggestion
T-values are not in the units of the original data, but unitless.
```

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +## References
Since this README has a lot of background information, it might make sense to distribute the references throughout the doc rather than all that the end so we know where to look if we need more information on a specific statement.

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +### Procedure
Is this meant to just be background information on how the t-test is calculated or is this supposed to be the procedure that someone has to go through to use this snippet?

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +t-distribution (also called Student's t-distribution) is a type of probability
```suggestion
T-distribution (also called Student's t-distribution) is a type of probability
```

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +z-test is used when comparing sample mean with large sample size to
```suggestion
A z-test is used when comparing sample mean with large sample size to
```

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +t-test is used to compare sample means with small sample size (< 30)
```suggestion
A t-test is used to compare sample means with small sample size (< 30)
```

2020-04-20 19:15 UTC, kkiesling commented on t_test/README.md
> +### `run_twosample_ttest.py`
There probably needs to be information here (or somewhere) that in order to just run the script like this, one has to edit some functions to properly parse the data (and list what those functions are).

2020-04-20 19:15 UTC, kkiesling commented on t_test/twosample_ttest.py
> +form {key: [Sample mean, Estimated standard error of the mean, sample size]}.
I'm a little confused by this structure. What is the "key" supposed to be? Can you give an example of what this looks like for a nuclear related problem? (and put this information in the README).

2020-04-20 19:15 UTC, kkiesling commented on t_test/twosample_ttest.py
> +def calc_twosample_tvalue(m1, sd1, n1, m2, sd2, n2, d):
Just so that I understand this correctly. If I wanted to do a t-test on two meshtallies, I would have to call this function for every single mesh voxel in the tally right?

2020-04-20 19:15 UTC, kkiesling commented on t_test/twosample_ttest.py
> +        d (float): Set discrepancy between two input data, if any.
"if any" implies this should be an optional argument.

2020-04-20 19:15 UTC, kkiesling commented on t_test/twosample_ttest.py
> +        n1 (float): Size of sample 1.
Theory understanding question: If this test is being run on a tally, is the sample size n the number of histories run in the simulation or only the number of histories that contributed to that tally?

2020-04-20 19:15 UTC, kkiesling commented on t_test/twosample_ttest.py
> +NDIGITS = 5  # Default precision after the decimal point.
Can these values be changed when running from the command line?

2020-04-22 21:47 UTC, ypark234 commented on t_test/README.md
> +## t-test?
My intention was: "(What is) t-test?"

2020-04-22 21:53 UTC, ypark234 commented on t_test/README.md
> +### Procedure
This is more like background information on how t-test is performed.
Most of them are already followed in the module.

2020-04-22 21:57 UTC, ypark234 commented on t_test/twosample_ttest.py
> +form {key: [Sample mean, Estimated standard error of the mean, sample size]}.
For example when you take data from mesh tally output file, keys can be a tuple of center coordinates (x, y, z) for that specific mesh.

2020-04-22 22:00 UTC, ypark234 commented on t_test/twosample_ttest.py
> +def calc_twosample_tvalue(m1, sd1, n1, m2, sd2, n2, d):
Yes, that's how it should work.
And the main `t_test` function will do the work for you, if you have properly parsed data.

2020-04-22 22:18 UTC, ypark234 commented on t_test/twosample_ttest.py
> +NDIGITS = 5  # Default precision after the decimal point.
I just gave a constant value as most available t-tables do not provide precision beyond 5.

2020-04-22 22:22 UTC, ypark234 commented on t_test/twosample_ttest.py
> +        n1 (float): Size of sample 1.
In theory, it should be the number of histories that actually contributed to that tally,
which I assume is hard/impossible to know from MCNP output? (correct me if I'm wrong!)

2020-04-22 22:30 UTC, ypark234 commented on t_test/README.md
> +## References
I'll try to categorize references according to relevant sections.

2020-04-25 16:47 UTC, gonuke commented on t_test/twosample_ttest.py
> +        n1 (float): Size of sample 1.
I think this should be the total number of histories.  The fact that some contribute a score of 0 is part of the distribution.

2020-05-15 18:46 UTC, kkiesling commented
@ypark234 do you want me to review this again or are we waiting on CI first?

2020-09-10 18:03 UTC, ypark234 commented
Sorry, let me do a final touch on this sooon and ask for possibly final review.

2020-09-16 22:59 UTC, ypark234 commented
It is finally ready for another review & merge.

2020-09-22 13:35 UTC, kkiesling approved these changes
This looks good to me

2020-10-14 02:52 UTC, kkiesling commented
pending approval from @bam241 and this could probably be merged?

2021-03-02 13:38 UTC, gonuke commented
Thanks @ypark234  - This is a great example of well-documented and complete code!

I think there are some design questions worth discussing, however, and might be great for a software meeting.  Primarily, I think the `twosample_ttest.py` should have a minimal set of functions to perform a t-test on data with a well defined structure, or variations for different well-defined structures.  The functions to load and format the data into those well-defined structures should live elsewhere like the script example you have provided.

For example, it seems like you have two well-defined structures right now: (1) a vector of data, (2) a grid of data.  For each of these, I would anticipate:
- a way to perform an element-wise t-test
- a way to plot the t-value or p-value
- a histogram of t-values or p-values

In addition to a script that demonstrates the basic functionality, we could also have scripts (different PRs) that apply this test to some standard data we use in CNERG, esp. MCNP mesh tallies.

2021-03-04 22:12 UTC, gonuke requested changes
Here is one little comment.

2021-03-04 22:12 UTC, gonuke commented on t_test/twosample_ttest.py
> +            reject = True
```suggestion
        reject = abs(t_val) > t_crit
```

2021-03-09 11:07 UTC, gonuke requested changes
Just one small suggestion- thanks @ypark234

2021-03-09 11:07 UTC, gonuke commented on scripts/run_twosample_ttest.py
> +def load_data(filename):
I suggest calling this function something like `load_mcnp_mesh_slice` to make it clear that it is data format specific.

You could also add `e` and `z` as arguments.

2021-03-14 14:51 UTC, gonuke approved these changes
Thanks @ypark234 - these last changes look great!

2021-03-14 14:51 UTC, merged